name: ci-pr

on:
  pull_request:
    branches: [master]

env:
  GO_VERSION: 1.17.10
  GOLANGCI_LINT_VERSION: v1.46.2
  GO_CACHE_PATH: "~/.cache/go"
  GO_CACHE_KEY: go

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - run: make lint

  proto-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: "14"
      - run: make proto-fmt-check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.GO_CACHE_PATH }}
          key: ${{ env.GO_CACHE_KEY }}
      - run: make build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.GO_CACHE_PATH }}
          key: ${{ env.GO_CACHE_KEY }}
      - run: make test
